server:
  port: 8085

spring:
  application:
    name: ai-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

services:
  student-url: http://STUDENT-SERVICE
  attendance-url: http://ATTENDANCE-SERVICE

# ─── Configuration Groq AI ───────────────────────────────────────────────────
groq:
  api-key: ${GROQ_API_KEY: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}
  api-url: https://api.groq.com/openai/v1/chat/completions
  model: llama-3.3-70b-versatile